apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secrets
  namespace: chat-app
type: Opaque
stringData:
  jwt: "sanskar"
  cloudapikey: "289512326838962"
  cloudapisecret: "9Fv-Zfycezarldn2XW5USLe95sk"
  cloudname: "talkativechatapp"
  mongourl: "mongodb://admin:admin@mongodb:27017/chatdb?authSource=admin"
